imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

    # Mopa Bootstrap
    - { resource: mopa/mopa_bootstrap.yml }

    # Knp Paginator
    - { resource: knp/knp_paginator.yml }

    # FriendOfSymfony Bundles
    #- { resource: fos/fos_comment.yml }
    - { resource: fos/fos_rest.yml }
    - { resource: fos/fos_user.yml }
    #- { resource: fos/fos_elastica.yml }

    #- { resource: bazinga/bazinga_hateos.yml }

    # Sonata Core Bundles
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_formatter.yml }
    - { resource: sonata/sonata_cache.yml }
    - { resource: sonata/sonata_seo.yml }
    - { resource: sonata/sonata_timeline.yml }
    - { resource: sonata/sonata_intl.yml }
    - { resource: sonata/sonata_core.yml }

    # Sonata Feature Bundles
    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_page.yml }
    - { resource: sonata/sonata_classification.yml }
    - { resource: sonata/sonata_media.yml }
    - { resource: sonata/sonata_news.yml }
    - { resource: sonata/sonata_user.yml }
    - { resource: sonata/sonata_notification.yml }

    # Sonata e-commerce bundles
    #- { resource: sonata/sonata_price.yml }
    #- { resource: sonata/sonata_order.yml }
    #- { resource: sonata/sonata_payment.yml }
    #- { resource: sonata/sonata_product.yml }
    #- { resource: sonata/sonata_invoice.yml }
    #- { resource: sonata/sonata_delivery.yml }
    #- { resource: sonata/sonata_customer.yml }
    #- { resource: sonata/sonata_basket.yml }

    - { resource: gedmo/doctrine_extensions.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'SonataCoreBundle:Form:datepicker.html.twig'
            - 'SonataFormatterBundle:Form:formatter.html.twig'

services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [SymbioOrangeGateAdminBundle]
    #java: /usr/bin/java
    filters:
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
            apply_to: "\.less$"
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration (needed for Jackalope Doctrine DBAL)
doctrine:
    dbal:
        driver:   "%database_driver%"
        charset:  UTF8
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        types:
            json:     Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
            translatable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Translatable\Entity
                # make sure vendor library location is correct
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity/MappedSuperclass"
            loggable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
            tree:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
            sortable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Sortable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Sortable/Entity"
        dql:
            numeric_functions:
                sin: Symbio\OrangeGate\AdminBundle\DQL\Sin
                asin: Symbio\OrangeGate\AdminBundle\DQL\Asin
                cos: Symbio\OrangeGate\AdminBundle\DQL\Cos
                acos: Symbio\OrangeGate\AdminBundle\DQL\Acos
                radians: Symbio\OrangeGate\AdminBundle\DQL\Radians
                power: Symbio\OrangeGate\AdminBundle\DQL\Power
                pi: Symbio\OrangeGate\AdminBundle\DQL\Pi
                regexp: Symbio\OrangeGate\AdminBundle\DQL\Regexp
                collate: Symbio\OrangeGate\AdminBundle\DQL\Collate
                cast: Symbio\OrangeGate\AdminBundle\DQL\Cast

# Menu Configuration
knp_menu:
    twig: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

lunetics_locale:
    allowed_locales:
        - en
        - cs
    guessing_order:
        - query
        - router
        - session
        - cookie
        - browser
    switcher:
        template: SymbioOrangeGateAdminBundle:Core:language_switcher.html.twig

# hearsay_require_js:
#     require_js_src:      /bundles/cbredefault/js/vendor/requirejs/require.js
#     initialize_template: HearsayRequireJSBundle::initialize.html.twig
#     base_url:            js
#     base_dir:            %kernel.root_dir%/../src/CBRE/DefaultBundle/Resources/public/js
#     optimizer:
#         path:                    %kernel.root_dir%/../src/CBREDefaultBundle/Resources/public/js/vendor/r.js/dist/r.js
#         hide_unoptimized_assets: false
#         almond_path:             ~

ivory_ck_editor:
    plugins:
        youtube:
            path: "/bundles/symbioorangegateadmin/plugins/youtube/"
            filename: "plugin.js"
    default_config: default
    configs:
        default:
            filebrowserBrowseRoute: admin_orangegate_media_media_browser
            filebrowserImageBrowseRoute: admin_orangegate_media_media_browser
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
            filebrowserUploadRoute: admin_orangegate_media_media_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
            filebrowserImageUploadRoute: admin_orangegate_media_media_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
                context: default
        formatter:
            toolbar: [["Styles"],["Bold","Italic","Underline","Subscript","Superscript","-","Cut","Copy","Paste","-","Undo","Redo","-","NumberedList","BulletedList","-","Outdent","Indent","-","Blockquote","-","Image", "Youtube","Link","Unlink","Table"],["Maximize","Source"]]
            filebrowserBrowseRoute: admin_orangegate_media_media_browser
            filebrowserImageBrowseRoute: admin_orangegate_media_media_browser
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
            filebrowserUploadRoute: admin_orangegate_media_media_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
            filebrowserImageUploadRoute: admin_orangegate_media_media_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
            format_tags: "p;h2;h3;h4;pre;address;div"
            extraAllowedContent: "h1 h2 h3 h4"
            stylesSet: [ { name: 'H2 Headline', element: 'h2' }, { name: 'H3 Headline', element: 'h3' }, { name: 'H4 Headline', element: 'h4' }, { name: 'Bold', element: 'strong' }, { name: 'Italic', element: 'em' }, { name: 'Underline', element: 'u' } ]
            extraPlugins: 'youtube'
        description:
            toolbar: [ [ "Source", "-", "Bold", "Italic", '-', "Anchor", '-', 'PasteFromWord', '-', 'Undo', 'Redo', '-', "Maximize" ] ]
            filebrowserBrowseRoute: admin_orangegate_media_media_browser
            filebrowserImageBrowseRoute: admin_orangegate_media_media_browser
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
            filebrowserUploadRoute: admin_orangegate_media_media_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
            filebrowserImageUploadRoute: admin_orangegate_media_media_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
                context: news

oneup_uploader:
    mappings:
        media_image:
            frontend: blueimp
            allowed_mimetypes: ["image/gif", "image/jpeg", "image/png"]
            error_handler: orangegate.upload.error_handler
        media_file:
            frontend: blueimp
            error_handler: orangegate.upload.error_handler

symbio_orange_gate_translation:
    locales: %symbio.orangegate.locales%
    required_locales: []
    templating: "SymbioOrangeGateAdminBundle:Form:translations.html.twig"

parameters:
    symbio.orangegate.locales: [cs, en]
    sonata.page.admin.page.class: Symbio\OrangeGate\PageBundle\Admin\PageAdmin
    sonata.page.admin.page.controller: SymbioOrangeGatePageBundle:PageAdmin
    sonata.page.admin.block.class: Symbio\OrangeGate\PageBundle\Admin\BlockAdmin
    sonata.page.request_listener.class: Symbio\OrangeGate\PageBundle\Listener\RequestListener
    sonata.page.admin.shared_block.class: Symbio\OrangeGate\PageBundle\Admin\SharedBlockAdmin
    sonata.page.admin.shared_block.controller: SymbioOrangeGatePageBundle:SharedBlockAdmin
    sonata.page.manager.site.class: Symbio\OrangeGate\PageBundle\Entity\SiteManager
    sonata.page.manager.page.class: Symbio\OrangeGate\PageBundle\Entity\PageManager
    sonata.page.manager.snapshot.class: Symbio\OrangeGate\PageBundle\Entity\SnapshotManager
    sonata.page.service.default.class: Symbio\OrangeGate\PageBundle\Page\OrangeGatePageService
    sonata.page.cms_manager_selector.class: Symbio\OrangeGate\PageBundle\CmsManager\CmsManagerSelector
    sonata.page.cms_manager.page.class: Symbio\OrangeGate\PageBundle\CmsManager\CmsPageManager
    sonata.page.cms_manager.snapshot.class: Symbio\OrangeGate\PageBundle\CmsManager\CmsSnapshotManager
    sonata.page.router.class: Symbio\OrangeGate\PageBundle\Route\CmsPageRouter
    sonata.page.transformer.class: Symbio\OrangeGate\PageBundle\Entity\Transformer
    sonata.page.admin.site.class: Symbio\OrangeGate\PageBundle\Admin\SiteAdmin
    sonata.page.site.selector.host_with_path.class: Symbio\OrangeGate\PageBundle\Site\HostPathSiteSelector
    sonata.page.block_interactor.class: Symbio\OrangeGate\PageBundle\Entity\BlockInteractor
    sonata.classification.admin.collection.class: Symbio\OrangeGate\ClassificationBundle\Admin\CollectionAdmin
    sonata.classification.admin.context.class: Symbio\OrangeGate\ClassificationBundle\Admin\ContextAdmin
    sonata.classification.admin.context.controller: SymbioOrangeGateClassificationBundle:ContextAdmin
    sonata.classification.admin.category.class: Symbio\OrangeGate\ClassificationBundle\Admin\CategoryAdmin
    sonata.classification.admin.category.controller: SymbioOrangeGateClassificationBundle:CategoryAdmin
    sonata.classification.admin.collection.controller: SymbioOrangeGateClassificationBundle:CollectionAdmin
    sonata.classification.manager.category.class: Symbio\OrangeGate\ClassificationBundle\Entity\CategoryManager
    sonata.user.admin.user.entity: Symbio\OrangeGate\UserBundle\Entity\User
    sonata.user.admin.group.entity: Symbio\OrangeGate\UserBundle\Entity\Group
    sonata.admin.object.manipulator.acl.admin.class: Symbio\OrangeGate\AdminBundle\Util\AdminObjectAclManipulator
    sonata.news.admin.post.entity: Symbio\OrangeGate\NewsBundle\Entity\Post
    sonata.news.admin.comment.entity: Symbio\OrangeGate\NewsBundle\Entity\Comment
    sonata.media.admin.media.controller: SymbioOrangeGateMediaBundle:MediaAdmin
    sonata.media.manager.media.class: Symbio\OrangeGate\MediaBundle\Entity\MediaManager
    sonata.media.resizer.simple.class: Symbio\OrangeGate\MediaBundle\Resizer\OrangeGateResizer
    sonata.page.block.shared_block.class: Symbio\OrangeGate\PageBundle\Block\SharedBlockBlockService

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600

sensio_framework_extra:
    request: { converters: true }
    view:    { annotations: false }
    router:  { annotations: true }
