imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

    # Mopa Bootstrap
    - { resource: mopa/mopa_bootstrap.yml }

    # Knp Paginator
    - { resource: knp/knp_paginator.yml }

    # FriendOfSymfony Bundles
    #- { resource: fos/fos_comment.yml }
    #- { resource: fos/fos_rest.yml }
    - { resource: fos/fos_user.yml }
    #- { resource: fos/fos_elastica.yml }

    #- { resource: bazinga/bazinga_hateos.yml }

    # Sonata Core Bundles
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_formatter.yml }
    - { resource: sonata/sonata_cache.yml }
    - { resource: sonata/sonata_seo.yml }
    - { resource: sonata/sonata_timeline.yml }
    - { resource: sonata/sonata_intl.yml }
    - { resource: sonata/sonata_core.yml }

    # Sonata Feature Bundles
    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_page.yml }
    - { resource: sonata/sonata_classification.yml }
    - { resource: sonata/sonata_media.yml }
    - { resource: sonata/sonata_news.yml }
    - { resource: sonata/sonata_user.yml }
    - { resource: sonata/sonata_notification.yml }

    # Sonata e-commerce bundles
    #- { resource: sonata/sonata_price.yml }
    #- { resource: sonata/sonata_order.yml }
    #- { resource: sonata/sonata_payment.yml }
    #- { resource: sonata/sonata_product.yml }
    #- { resource: sonata/sonata_invoice.yml }
    #- { resource: sonata/sonata_delivery.yml }
    #- { resource: sonata/sonata_customer.yml }
    #- { resource: sonata/sonata_basket.yml }

    - { resource: gedmo/doctrine_extensions.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'SonataCoreBundle:Form:datepicker.html.twig'
            - 'SonataFormatterBundle:Form:formatter.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [SymbioOrangeGateAdminBundle]
    #java: /usr/bin/java
    filters:
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
            apply_to: "\.less$"
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration (needed for Jackalope Doctrine DBAL)
doctrine:
    dbal:
        driver:   "%database_driver%"
        charset:  UTF8
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        types:
            json:     Sonata\Doctrine\Types\JsonType
            currency: Sonata\Component\Currency\CurrencyDoctrineType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
            translatable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Translatable\Entity
                # make sure vendor library location is correct
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity/MappedSuperclass"
            loggable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
            tree:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
        dql:
            numeric_functions:
                sin: Symbio\OrangeGate\AdminBundle\DQL\Sin
                asin: Symbio\OrangeGate\AdminBundle\DQL\Asin
                cos: Symbio\OrangeGate\AdminBundle\DQL\Cos
                acos: Symbio\OrangeGate\AdminBundle\DQL\Acos
                radians: Symbio\OrangeGate\AdminBundle\DQL\Radians
                power: Symbio\OrangeGate\AdminBundle\DQL\Power
                pi: Symbio\OrangeGate\AdminBundle\DQL\Pi

# Menu Configuration
knp_menu:
    twig: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

lunetics_locale:
    allowed_locales:
        - en
        - cs
    guessing_order:
        - query
        - router
        - session
        - cookie
        - browser
    switcher:
        template: SymbioOrangeGateAdminBundle:Core:language_switcher.html.twig

# hearsay_require_js:
#     require_js_src:      /bundles/cbredefault/js/vendor/requirejs/require.js
#     initialize_template: HearsayRequireJSBundle::initialize.html.twig
#     base_url:            js
#     base_dir:            %kernel.root_dir%/../src/CBRE/DefaultBundle/Resources/public/js
#     optimizer:
#         path:                    %kernel.root_dir%/../src/CBREDefaultBundle/Resources/public/js/vendor/r.js/dist/r.js
#         hide_unoptimized_assets: false
#         almond_path:             ~

ivory_ck_editor:
    default_config: default
    configs:
        default:
            filebrowserBrowseRoute: admin_orangegate_media_media_browser
            filebrowserImageBrowseRoute: admin_orangegate_media_media_browser
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
            filebrowserUploadRoute: admin_orangegate_media_media_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
            filebrowserImageUploadRoute: admin_orangegate_media_media_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
                context: default
        description:
            toolbar: [ [ "Source", "-", "Bold", "Italic", '-', "Anchor", '-', 'PasteFromWord', '-', 'Undo', 'Redo', '-', "Maximize" ] ]
            filebrowserBrowseRoute: admin_orangegate_media_media_browser
            filebrowserImageBrowseRoute: admin_orangegate_media_media_browser
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
            filebrowserUploadRoute: admin_orangegate_media_media_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
            filebrowserImageUploadRoute: admin_orangegate_media_media_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
                context: news

a2lix_translation_form:
    locales: %symbio.orangegate.locales%
    required_locales: []
    templating: "SymbioOrangeGateAdminBundle:Form:translations.html.twig"

parameters:
    symbio.orangegate.locales: [cs, en]
    sonata.page.admin.page.class: Symbio\OrangeGate\PageBundle\Admin\PageAdmin
    sonata.page.admin.block.class: Symbio\OrangeGate\PageBundle\Admin\BlockAdmin
    sonata.page.request_listener.class: Symbio\OrangeGate\PageBundle\Listener\RequestListener
    sonata.page.service.default.class: Symbio\OrangeGate\PageBundle\Page\OrangeGatePageService
    sonata.page.cms_manager.page.class: Symbio\OrangeGate\PageBundle\CmsManager\CmsPageManager
    sonata.page.cms_manager.snapshot.class: Symbio\OrangeGate\PageBundle\CmsManager\CmsSnapshotManager
    sonata.page.router.class: Symbio\OrangeGate\PageBundle\Route\CmsPageRouter
    sonata.classification.admin.collection.class: Symbio\OrangeGate\ClassificationBundle\Admin\CollectionAdmin
    sonata.user.admin.user.entity: Symbio\OrangeGate\UserBundle\Entity\User
    sonata.user.admin.group.entity: Symbio\OrangeGate\UserBundle\Entity\Group
    sonata.admin.object.manipulator.acl.admin.class: Symbio\OrangeGate\AdminBundle\Util\AdminObjectAclManipulator
    sonata.news.admin.post.entity: Symbio\OrangeGate\NewsBundle\Entity\Post
    sonata.news.admin.comment.entity: Symbio\OrangeGate\NewsBundle\Entity\Comment
    sonata.media.resizer.simple.class: Symbio\OrangeGate\MediaBundle\Resizer\OrangeGateResizer