#
# more information can be found here http://sonata-project.org/bundles/admin
#
sonata_admin:
    # default value, change it to sonata.admin.security.handler.acl to use ACL
    security:
        handler: sonata.admin.security.handler.acl
        # acl security information
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]

    title:      OrangeGate4

    options:
        html5_validate: false # does not use html5 validation
        pager_links: 5 # pager max links to display
        title_mode: single_text

    templates:
        layout:  SymbioOrangeGateAdminBundle::standard_layout.html.twig
        list:    SymbioOrangeGateAdminBundle:CRUD:list.html.twig

    assets:
        stylesheets:
            - 'bundles/sonatacore/vendor/bootstrap/dist/css/bootstrap.min.css'
            - 'bundles/sonatacore/vendor/components-font-awesome/css/font-awesome.min.css'
            - 'bundles/sonatacore/vendor/ionicons/css/ionicons.min.css'
            - 'bundles/sonataadmin/vendor/admin-lte/dist/css/AdminLTE.css'
            - 'bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-blue.min.css'
            - 'bundles/sonataadmin/vendor/iCheck/skins/flat/blue.css'
            - 'bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css'
            - 'bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css'
            - 'bundles/sonatacore/vendor/select2/select2.css'
            - 'bundles/sonatacore/vendor/select2/select2-bootstrap.css'
            - 'bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css'
            - 'bundles/sonataformatter/markitup/skins/sonata/style.css'
            - 'bundles/sonataformatter/markitup/sets/html/style.css'
            - 'bundles/sonataformatter/markitup/sets/textile/style.css'
            - 'bundles/sonataadmin/css/styles.css'
            - 'bundles/sonataadmin/css/layout.css'
            - 'bundles/sonataadmin/css/tree.css'
            - 'bundles/sonatapage/sonata-page.back.min.css'
            - 'bundles/symbioorangegateadmin/css/flags.css'
            - 'bundles/symbioorangegateadmin/css/og.css'
        javascripts:
            - 'bundles/sonatacore/vendor/jquery/dist/jquery.min.js'
            - 'bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js'
            - 'bundles/sonatacore/vendor/moment/min/moment.min.js'
            - 'bundles/sonatacore/vendor/bootstrap/dist/js/bootstrap.min.js'
            - 'bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js'
            - 'bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js'
            - 'bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js'
            - 'bundles/sonataadmin/vendor/jquery-form/jquery.form.js'
            - 'bundles/sonataadmin/jquery/jquery.confirmExit.js'
            - 'bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js'
            - 'bundles/sonatacore/vendor/select2/select2.min.js'
            - 'bundles/sonataadmin/vendor/admin-lte/dist/js/app.min.js'
            - 'bundles/sonataadmin/vendor/iCheck/icheck.min.js'
            - 'bundles/sonataadmin/vendor/slimScroll/jquery.slimscroll.min.js'
            - 'bundles/ivoryckeditor/ckeditor.js'
            - 'bundles/sonataformatter/vendor/markitup-markitup/markitup/jquery.markitup.js'
            - 'bundles/sonataformatter/markitup/sets/html/set.js'
            - 'bundles/sonataformatter/markitup/sets/textile/set.js'
            - 'bundles/sonataadmin/Admin.js'
            - 'bundles/sonataadmin/treeview.js'
            - 'bundles/symbioorangegatepage/js/sonata-page.back.js'
            - 'bundles/symbioorangegatemedia/js/jquery-file-upload/jquery.iframe-transport.js'
            - 'bundles/symbioorangegatemedia/js/jquery-file-upload/jquery.fileupload.js'

    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }
#            - { position: right, type: sonata.admin_doctrine_orm.block.audit}
#            - { position: top, type: sonata.block.service.text, settings: { content: '<h2>Welcome to the OrangeGate4 CMS!</h2>'} }
            - { position: right, type: sonata.timeline.block.timeline, settings: { context: SONATA_ADMIN, title: Poslední změny, max_per_page: 15 }}
#            - { position: right, type: orangegate.news.block.recent_posts, settings: { title: Recent Posts, number: 3, mode: admin }}
#            - { position: right, type: orangegate.news.block.recent_comments, settings: { title: Recent Comments, number: 5, mode: admin, template: SymbioOrangeGateNewsBundle:Block: }}
#            - { position: right, type: sonata.order.block.recent_orders, settings: { title: Recent Orders, number: 5, mode: admin }}
#            - { position: right, type: sonata.customer.block.recent_customers, settings: { title: Recent Customers, number: 5, mode: admin }}

        groups:
            sonata.admin.group.site:
                label:           sonata_site
                label_catalogue: SymbioOrangeGateAdminBundle
                icon: '<i class="fa fa-puzzle-piece"></i>'
                items:
                    - sonata.page.admin.page
                    - sonata.page.admin.site
                    - sonata.page.admin.shared_block

            sonata.admin.group.content:
                label:           sonata_content
                label_catalogue: SymbioOrangeGateAdminBundle
                icon: '<i class="fa fa-th"></i>'
                items:
                    - orangegate.news.admin.post
                    #- orangegate.news.admin.comment
                    - orangegate.admin.token
                    - orangegate.media.admin.media
                    #- orangegate.media.admin.gallery
                    #- sonata.comment.admin.thread

            #sonata.admin.group.ecommerce:
            #    label:           sonata_ecommerce
            #    label_catalogue: SonataAdminBundle
            #    items:
            #        - sonata.customer.admin.customer
            #        - sonata.invoice.admin.invoice
            #        - sonata.order.admin.order
            #        - sonata.product.admin.product

            sonata.admin.group.classification:
                label:           sonata_classification
                label_catalogue: SonataClassificationBundle
                items:
                    - sonata.classification.admin.context
                    - sonata.classification.admin.category
                    #- orangegate.classification.admin.tag
                    - sonata.classification.admin.collection

            sonata.admin.group.administration:
                label:           sonata_administration
                label_catalogue: SymbioOrangeGateAdminBundle
                icon: '<i class="fa fa-gears"></i>'
                items:
                    - orangegate.user.admin.user
                    - orangegate.user.admin.group
                    #- sonata.notification.admin.message

sonata_doctrine_orm_admin:
    templates:
        form: [ SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig, SymbioOrangeGateMediaBundle:Form:form_admin_fields.html.twig ]
