#
# more information can be found here http://sonata-project.org/bundles/news
#
sonata_news:
    title:        Test blog
    link:         test-link
    description:  Test blog description
    salt:         test-alt

    # permalink_generator: sonata.news.permalink.category # /party/new-year
    permalink_generator: sonata.news.permalink.date # /2011/12/31/new-year

    # comment options
    comment:
        notification:
            emails:   [test@email.com]
            from:     Test From
            template: 'SonataNewsBundle:Mail:comment_notification.txt.twig'

    class:
        post: Symbio\OrangeGate\NewsBundle\Entity\Post
        comment: Symbio\OrangeGate\NewsBundle\Entity\Comment
        user: Symbio\OrangeGate\UserBundle\Entity\User

# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SymbioOrangeGateNewsBundle: ~
                    SonataNewsBundle: ~

ivory_ck_editor:
    configs:
        news:
            filebrowserBrowseRoute: admin_orangegate_media_media_browser
            filebrowserImageBrowseRoute: admin_orangegate_media_media_browser
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
            filebrowserUploadRoute: admin_orangegate_media_media_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
            filebrowserImageUploadRoute: admin_orangegate_media_media_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
                context: news
