#
# more information can be found here http://sonata-project.org/bundles/page
#

cmf_routing:
    chain:
        routers_by_id:
            #cmf_routing.dynamic_router: 200
            sonata.page.router: 150
            router.default: 100

sonata_page:
    multisite:             host_with_path # host
    use_streamed_response: false # set the value to false in debug mode or if the reverse proxy does not handle streamed response
    slugify_service:       sonata.core.slugify.cocur

    ignore_uri_patterns:
        - ^/admin\/
        - ^/api\/

    ignore_route_patterns:
        - ^(.*)admin(.*)     # ignore admin route, ie route containing 'admin'
        - ^_(.*)            # ignore symfony routes
        - ^sonata_user_(.*)
        - ^fos_user_(.*)
        - ^sonata_media_(.*)
        - ^sonata_page_(.*)

    ignore_routes:
        - sonata_page_cache_esi
        - sonata_page_cache_ssi
        - sonata_page_js_sync_cache
        - sonata_page_js_async_cache
        - sonata_cache_esi
        - sonata_cache_ssi
        - sonata_cache_js_async
        - sonata_cache_js_sync
        - sonata_cache_apc
        - sonata_cache_symfony
        - sonata_news_add_comment
        - sonata_news_archive_monthly
        - sonata_news_tag
        - sonata_news_collection
        - sonata_news_archive_yearly
        - sonata_news_archive
        - sonata_news_comment_moderation

    cache_invalidation:
        service:  sonata.page.cache.invalidation.simple
        recorder: sonata.page.cache.recorder
        classes:
            "Symbio\OrangeGate\PageBundle\Entity\Block": getId

    class:
        page: Symbio\OrangeGate\PageBundle\Entity\Page
        snapshot: Symbio\OrangeGate\PageBundle\Entity\Snapshot
        block: Symbio\OrangeGate\PageBundle\Entity\Block
        site: Symbio\OrangeGate\PageBundle\Entity\Site

    default_template: default

    assets:
        stylesheets:
            - bundles/sonataadmin/vendor/bootstrap/dist/css/bootstrap.min.css
            - bundles/sonatapage/default.css
        javascripts:
            - bundles/sonatacore/vendor/jquery/dist/jquery.min.js
            - bundles/sonatacore/vendor/bootstrap/dist/js/bootstrap.min.js
            - bundles/sonatapage/page.js

    templates:
        default:  { path: 'SonataPageBundle::layout.html.twig', name: 'default' }

    page_defaults:
        homepage: { decorate: true, enabled: true }

    #caches:
    #    esi:
    #        token:    add an unique token here # default is a random value
    #        version:  3                        # version 3 is the default on debian wheezy ...
    #        servers:
    #            # you need to ajust this configuration to match your varnish configuration
    #            - %sonata_page.varnish.command%
    #    ssi:
    #        token:    add an unique token here # default is a random value

    catch_exceptions:
        not_found: [404]    # render 404 page with "not_found" key (name generated: _page_internal_error_{key})
        fatal:     [500]    # so you can use the same page for different http errors or specify specific page for each error


# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SymbioOrangeGatePageBundle: ~
                    SonataPageBundle: ~
