# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataCustomerBundle: ~
                    SonataCustomerBundle: ~

sonata_customer:
    class:
        user: Symbio\OrangeGate\UserBundle\Entity\User