services:
    orangegate.news.admin.post:
        class: Symbio\OrangeGate\NewsBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Content, label: posts }
        arguments: [null, Symbio\OrangeGate\NewsBundle\Entity\Post, null]
        calls:
            - [setTranslationDomain, [%sonata.news.admin.post.translation_domain%]]
            - [setPermalinkGenerator, [@orangegate.news.permalink.generator]]

