services:
    orangegate.media.admin.media:
      class: Symbio\OrangeGate\MediaBundle\Admin\MediaAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Content, label: media }
      arguments: [null, Symbio\OrangeGate\MediaBundle\Entity\Media, %sonata.media.admin.media.controller%, @sonata.media.pool, @sonata.classification.manager.category]
      calls:
        - [ setModelManager, [@sonata.media.admin.media.manager] ]
        - [ setTranslationDomain, [%sonata.media.admin.media.translation_domain%] ]
        - [ setTemplates, [{inner_list_row: SonataMediaBundle:MediaAdmin:inner_row_media.html.twig, base_list_field: SonataAdminBundle:CRUD:base_list_flat_field.html.twig, list: SonataMediaBundle:MediaAdmin:list.html.twig, edit: SonataMediaBundle:MediaAdmin:edit.html.twig}] ]

    orangegate.media.admin.gallery:
      class: Symbio\OrangeGate\MediaBundle\Admin\GalleryAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Content, label: galleries }
      arguments: [null, Symbio\OrangeGate\MediaBundle\Entity\Gallery, %sonata.media.admin.gallery.controller%, @sonata.media.pool]
      calls:
        - [ setTranslationDomain, [%sonata.media.admin.media.translation_domain%] ]
        - [ setTemplates, [{list: SonataMediaBundle:GalleryAdmin:list.html.twig}] ]
