<?php
/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symbio\OrangeGate\PageBundle\Entity;

use Sonata\PageBundle\Entity\BaseSnapshot as BaseSnapshot;
use Doctrine\ORM\Mapping as ORM;
use Sonata\PageBundle\Model\PageInterface;
use Sonata\PageBundle\Model\SiteInterface;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 *
 * @ORM\Entity
 * @ORM\Table(name="page__snapshot")
 */
class Snapshot extends BaseSnapshot
{

    /**
     * @var integer $id
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var \Symbio\OrangeGate\PageBundle\Entity\Site
     */
    protected $site;

    /**
     * @var \Symbio\OrangeGate\PageBundle\Entity\Page
     */
    protected $page;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set site
     *
     * @param \Symbio\OrangeGate\PageBundle\Entity\Site $site
     * @return Snapshot
     */
    public function setSite(SiteInterface $site = null)
    {
        $this->site = $site;

        return $this;
    }

    /**
     * Get site
     *
     * @return \Symbio\OrangeGate\PageBundle\Entity\Site
     */
    public function getSite()
    {
        return $this->site;
    }

    /**
     * Set page
     *
     * @param \Symbio\OrangeGate\PageBundle\Entity\Page $page
     * @return Snapshot
     */
    public function setPage(PageInterface $page = null)
    {
        $this->page = $page;

        return $this;
    }

    /**
     * Get page
     *
     * @return \Symbio\OrangeGate\PageBundle\Entity\Page
     */
    public function getPage()
    {
        return $this->page;
    }
}
