<?php

namespace Symbio\OrangeGate\TranslationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LanguageTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageTokenRepository extends EntityRepository
{
}
